defauls: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pgadmin
  password: devel
  host: localhost

development:
  <<: *defaults
  database: gtgraphics_development

test:
  <<: *defaults
  database: gtgraphics_test