development:
  adapter: postgresql
  encoding: unicode
  database: gtgraphics_development
  pool: 5
  username: pgadmin
  password: devel
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gtgraphics_test
  pool: 5
  username: pgadmin
  password: devel
  host: localhost