defaults: &defaults
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  username: pgadmin
  password: devel

development:
  <<: *defaults
  host: localhost
  database: gtgraphics_development

test:
  <<: *defaults
  host: localhost
  database: gtgraphics_test

staging:
  <<: *defaults

production:
  <<: *defaults
  host: localhost
  database: gtgraphics_development
